In [1]:
import numpy as np 
import pandas as pd 
import re
import nltk 

In [2]:
#Read the training data into a data frame 
reviews = pd.read_json("data_train.json")

stars  useful  funny  cool  \
0      1       6      1     0   
1      5       0      0     0   
2      5       3      0     0   
3      5       0      0     0   
4      1       7      0     0   

                                                text                date  
0  Total bill for this horrible service? Over $8G... 2013-05-07 04:34:36  
1  I *adore* Travis at the Hard Rock's new Kelly ... 2017-01-14 21:30:33  
2  I have to say that this office really has it t... 2016-11-09 20:09:03  
3  Went in for a lunch. Steak sandwich was delici... 2018-01-09 20:56:38  
4  Today was my second out of three sessions I ha... 2018-01-30 23:07:38

In [3]:
# Holds all the features/ text attribute within each review
features = reviews.iloc[:, 4].values

# Holds the stars for each review
labels = reviews.iloc[:, 0].values

In [4]:
#An array that holds every review once it is processed
processed_reviews = []

In [5]:
for sentence in range(0, len(features)):
    # Remove all the special characters
    processed_text = re.sub(r'\W', ' ', str(features[sentence]))

    # remove all single characters
    processed_text= re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_text)

    # Substituting multiple spaces with single space
    processed_text = re.sub(r'\s+', ' ', processed_text, flags=re.I)

    # Converting to Lowercase
    processed_text = processed_text.lower()

    #Add the processed review to the array of processed reviews
    processed_reviews.append(processed_text)

In [8]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
# Tfidf vectorizert with the 2500 most common unique words
# Only counts words that appear in at least 7 reviews
# Only counts words that appear in less than 80% of reviews
# Remove all english stop words
vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))
processed_reviews = vectorizer.fit_transform(processed_reviews).toarray()

NameError: name 'TfidfVectorizer' is not defined

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# Hold out 20% of the train data to use it to test
X_train, X_test, y_train, y_test = train_test_split(processed_reviews, labels, test_size=0.2, random_state=0)

In [14]:
# Generate the model using the Logistic Regression classifier
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)

/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
#Predict on the test data 
y_pred = clf.predict(X_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 8073   554   282   220   614]
 [ 1969  1179  1118   655   554]
 [  708   570  2294  2651  1188]
 [  288   121   842  6650  6841]
 [  323    46   168  2780 26171]]
              precision    recall  f1-score   support

           1       0.71      0.83      0.77      9743
           2       0.48      0.22      0.30      5475
           3       0.49      0.31      0.38      7411
           4       0.51      0.45      0.48     14742
           5       0.74      0.89      0.81     29488

    accuracy                           0.66     66859
   macro avg       0.59      0.54      0.55     66859
weighted avg       0.64      0.66      0.64     66859

0.663590541288383
